Prevent crash with missing contactGroupMembership
This fixes errors like these:

```
Traceback (most recent call last):
  File "sync.py", line 495, in <module>
    groupRNs = [
  File "sync.py", line 498, in <listcomp>
    if grp["contactGroupMembership"]["contactGroupId"] != "myContacts"
KeyError: 'contactGroupMembership'
```

The reason for the crash is that not every dictionary in the list has a `contactGroupMembership` key:
```
[{'contactGroupMembership': {'contactGroupId': 'xxxx', ...}}, ... {'domainMembership': {'inViewerDomain': True}}]
```